import java.util.Scanner;

public class EXAM1_1s21 {
	public static void main(String[] args) {
		Scanner teclado=new Scanner(System.in);

		System.out.println(" 1.- Escribir un programa que escriba un rectangulo de 4x9 asteriscos, utilizando el caracter asterisco (*)");
		System.out.println();
		System.out.println("*********");
		System.out.println("*       *");
		System.out.println("*       *");
		System.out.println("*********");
	}
}